name: 'Objectstore Upload'
description: 'Objectstore upload action for DownToZero.cloud'
inputs:
  context_id:
    description: 'context id'
    required: true
  api_key:
    description: 'api key'
    required: true
  name:
    description: 'name of the artifact'
    required: true
  object_key:
    description: 'key of the objectstore, if empty name will be used'
    required: false
runs:
  using: "composite"
  steps:
    - name: uploading with object_key
      if: ${{ inputs.object_key != '' }}
      run: |
        curl -X 'PUT' -L 'https://objectstore.dtz.rocks/api/2022-11-28/obj/${{ inputs.object_key }}'   -H 'accept: */*'   -H 'X-API-KEY: ${{ inputs.api_key }}'   -H 'X-DTZ-CONTEXT: ${{ inputs.context_id }}' --data-binary @${{ inputs.name }} 
      shell: bash
    - name: uploading with artifact name
      if: ${{ inputs.object_key == '' }}
      run: |
        curl -X 'PUT' -L 'https://objectstore.dtz.rocks/api/2022-11-28/obj/${{ inputs.name }}'   -H 'accept: */*'   -H 'X-API-KEY: ${{ inputs.api_key }}'   -H 'X-DTZ-CONTEXT: ${{ inputs.context_id }}' --data-binary @${{ inputs.name }} 
      shell: bash
